Account/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout

from Account import views

urlpatterns = [
    url(r'^login', views.connexion, name='Connexion'),
    url(r'^logout$', logout, {'next_page': '/index/'}, name='Deconnexion'),

    url(r'^clien_compte', views.inscription_acheteur, name='AcheteurInscri'),
    url(r'^vendeur_compte', views.inscription_vendeur, name='VendeurInscri'),

    url(r'^password/update', views.update_Password, name='U_MDP'),

    url(r'^demande/read', views.demande_vendeur, name='R_Demande_Vendeur'),
]

Marketplace/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^accounts/', include('Account.urls')),
    url(r'^dChamps/', include('Dynamic_Champs.urls')),
    url(r'^acheteur/', include('Acheteur.urls')),
    url(r'^vendeur/', include('Vendeur.urls')),
    url(r'^article/', include('Article.urls')),
    url(r'^rel_ach_art/', include('Relation_Acheteur_Article.urls')),

    url(r'^index/', views.Index, name='accueil'),
    url(r'^index_admin', views.IndexAmdin, name='accueil_admin'),
    url(r'^mail', views.mail, name=''),
    # url(r'^admin/', admin.site.urls),
    url(r'^', views.Index, name=''),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Vendeur/urls.py
from django.conf.urls import url

from Vendeur import views

urlpatterns = [
    url(r'^profil/update', views.update_profil_vendeur, name='U_Profil_Vendeur'),

    url(r'^boutique/update', views.update_boutique, name='U_Boutique'),
    url(r'^boutique/all', views.read_boutique, name='R_All_Boutique'),
    url(r'^boutique/(?P<boutique_id>([0-9]+))/read', views.read_boutique, name='R_Boutique'),
    url(r'^boutique/(?P<boutique_id>([0-9]+))/delete', views.delete_boutique, name='D_Boutique'),
]

Article/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

from Dynamic_Champs.models import Marque, Categorie
from Traitement.compression import compression_size_photo
from Vendeur.models import Boutique


def produit_directory_path(instance, filename):
    return 'Produits/{0}/{1}/'.format(instance.boutique_prod_id.nom_bout, filename)


class Produit(models.Model):
    ETAT = (
        ('N', "Nouveau"),
        ('O', "Occasion")
    )

    boutique_prod_id = models.ForeignKey(
        Boutique,
        on_delete=models.CASCADE,
    )
    titre_prod = models.CharField(
        max_length=254
    )
    ref_prod = models.CharField(
        max_length=254
    )
    marque_prod_id = models.ForeignKey(
        Marque,
        on_delete=models.CASCADE,
    )
    categorie_prod_id = models.ForeignKey(
        Categorie,
        on_delete=models.CASCADE,
    )
    description_prod = models.TextField(
        blank=True
    )
    prix_original_prod = models.DecimalField(
        max_digits=9,
        decimal_places=3,
        validators=[
            MinValueValidator(
                limit_value=0,
                message="Le prix ne peut pas être négative!!"
            )
        ]
    )
    pourcentage_solde_prod = models.DecimalField(
        max_digits=6,
        decimal_places=3,
        blank=True,
        default=0,
        validators=[
            MinValueValidator(
                limit_value=0,
                message="Le pourcentage ne peut pas être négative!!"
            ),
            MaxValueValidator(
                limit_value=99,
                message="Valeur de pourcentage très élevé"
            )
        ]
    )
    quantite_stock_prod = models.PositiveSmallIntegerField()
    quantite_vendue_prod = models.PositiveSmallIntegerField(
        default=0
    )
    condition_prod = models.CharField(
        max_length=1,
        choices=ETAT
    )
    image_prod = models.ImageField(
        upload_to=produit_directory_path
    )
    nbr_avis_prod = models.PositiveSmallIntegerField(
        default=0
    )
    note_avis_prod = models.DecimalField(
        max_digits=2,
        decimal_places=1,
        default=0
    )

    def __str__(self):
        return self.titre_prod.capitalize()

    def save(self, *args, **kwargs):
        try:
            this = Produit.objects.get(id=self.id)
            if this.image_prod != self.image_prod:
                this.image_prod.delete(save=False)
        except:
            pass
        super(Produit, self).save(*args, **kwargs)
        # Compression du l'image du produit (max_widh = max_height = 512px)
        compression_size_photo(src=self.image_prod, size=512)

    def delete(self, using=None, keep_parents=False):
        this = Produit.objects.get(id=self.id)
        this.image_prod.delete(save=False)
        super(Produit, self).delete()



class Specification_Produit(models.Model):
    kle_value_spec_prod = models.TextField()
    produit_spec_prod = models.OneToOneField(
        Produit,
        on_delete=models.CASCADE,
    )

Vendeur/models.py
from django.contrib.auth.models import User
from django.db import models

from Dynamic_Champs.models import Pays


class Vendeur(User):
    registre_commerce_bout = models.CharField(
        max_length=100
    )

    def __str__(self):
        return self.first_name.title() + " " + self.last_name.capitalize()


class Boutique(models.Model):
    vendeur_bout_id = models.OneToOneField(
        Vendeur,
        on_delete=models.CASCADE,
    )
    nom_bout = models.CharField(
        max_length=254
    )
    adresse_bout = models.CharField(
        max_length=254,
        blank=True
    )
    description_bout = models.TextField(
        null=True,
        blank=True
    )
    pays_bout_id = models.ForeignKey(
        Pays
    )
    logo_bout = models.ImageField(
        upload_to="logo_boutique/",
        blank=True
    )

    def __str__(self):
        return self.nom_bout.capitalize()

    def save(self, *args, **kwargs):
        try:
            this = Boutique.objects.get(id=self.id)
            if this.logo_bout != self.logo_bout:
                this.logo_bout.delete(save=False)
        except:
            pass
        super(Boutique, self).save(*args, **kwargs)

Vendeur/forms.py
from django import forms
from django.http import HttpResponse

from Vendeur.models import Vendeur, Boutique


class VendeurProfilForm(forms.ModelForm):
    class Meta:
        model = Vendeur
        fields = [
            'last_name',
            'first_name',
            'email',
            'username',
        ]
        labels = {
            'last_name': "Nom",
            'first_name': "Prénom",
            'email': "E-Mail",
            'username': "Pseudo"
        }
        widgets = {
            'last_name': forms.TextInput(
                attrs={
                    'class': "form-control"
                }
            ),
            'first_name': forms.TextInput(
                attrs={

                    'class': "form-control"
                }
            ),
            'email': forms.EmailInput(
                attrs={
                    'class': "form-control"
                }
            ),
            'username': forms.TextInput(
                attrs={
                    'class': "form-control"
                }
            )
        }


class BoutiqueForm(forms.ModelForm):
    class Meta:
        model = Boutique
        fields = [
            'nom_bout',
            'description_bout',
            'adresse_bout',
            'pays_bout_id',
            'logo_bout'
        ]
        labels = {
            'nom_bout': "Nom du Boutique",
            'description_bout': "A propos de votre boutique",
            'adresse_bout': "Adresse",
            'pays_bout_id': "Pays",
            'logo_bout': "Logo"
        }
        widgets = {
            'nom_bout': forms.TextInput(
                attrs={
                    'autocomplete': "off",
                    'class': "form-control"
                }
            ),
            'description_bout': forms.Textarea(
                attrs={
                    'class': "form-control"
                }
            ),
            'adresse_bout': forms.TextInput(
                attrs={
                    'class': "form-control"
                }
            ),
            'pays_bout_id': forms.Select(
                attrs={
                    'class': "form-control"
                }
            ),
            'logo_bout': forms.FileInput(
                attrs={
                    'accept': "image/*"
                }
            )
        }

    def __init__(self, **kwargs):
        try:
            if not kwargs['instance'].logo_bout:
                self.base_fields['logo_bout'].widget.attrs['required'] = ""
        except:
            pass

        super(BoutiqueForm, self).__init__(**kwargs)

Vendeur/views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.decorators.cache import never_cache

from Account.permission import is_vendeur
from Traitement.compression import compression_size_photo
from Vendeur.forms import VendeurProfilForm, BoutiqueForm
from Vendeur.models import Vendeur, Boutique


@never_cache
@user_passes_test(is_vendeur)
def update_profil_vendeur(request):
    # recuperer les données du vendeur qui correspond à l'id passer en url
    vendeur_obj = get_object_or_404(Vendeur, pk=request.user.id)

    # recuperer les donners du formulaire sinon l'initialiser avec les donners du DB
    vendeurProfilForm = VendeurProfilForm(
        data=request.POST or None,
        instance=vendeur_obj
    )

    # si le formulaire a été envoyer
    if request.method == 'POST':
        if vendeurProfilForm.is_valid():
            vendeurProfilForm.save()


    # Sinon
    return render(
        request,
        'Vendeur/U_Profil_Vendeur.html',
        {
            'form': vendeurProfilForm,
            'id': request.user.id
        }
    )


@never_cache
@user_passes_test(is_vendeur)
def update_boutique(request):
    # si le boutique existe déja
    try:
        # récuperer les données du boutiques de celui connecter
        boutique_obj = get_object_or_404(Boutique, vendeur_bout_id_id=request.user.vendeur.id)
        # initiliser le formulaire avec ces données
        boutiqueForm = BoutiqueForm(
            data=request.POST or None,
            files=request.FILES or None,
            instance=boutique_obj
        )
    # Sinon
    except:
        # initiliser le formulaire
        boutiqueForm = BoutiqueForm(
            data=request.POST or None,
            files=request.FILES or None,
        )

    # si le formualire a été envoyer
    if request.method == 'POST':
        if boutiqueForm.is_valid():
            new_boutique_obj = boutiqueForm.save(commit=False)
            new_boutique_obj.vendeur_bout_id = Vendeur.objects.get(pk=request.user.vendeur.id)
            new_boutique_obj.save()

            # Compression du l'image logo (max_widh = max_height = 512px)
            compression_size_photo(src=new_boutique_obj.logo_bout, size=512)

            return HttpResponseRedirect(
                reverse(
                    'R_Boutique',
                    kwargs={
                        'boutique_id': new_boutique_obj.id
                    }
                )
            )

    # Sinon
    return render(
        request,
        'Vendeur/U_Boutique.html',
        {
            'form': boutiqueForm
        }
    )


@never_cache
def read_boutique(request, boutique_id=0):
    # afficher tous les boutiques
    if boutique_id == 0:
        # recuperer les informations des boutiques existantes
        boutique_list = Boutique.objects.all()

        return render(
            request,
            'Vendeur/R_All_Boutique.html',
            {
                'boutiques': boutique_list
            }
        )

    # afficher une seul boutique
    else:
        # recuperer les informations du boutique avec l'id la valeur 'boutique_id' passer en url
        boutique_obj = get_object_or_404(Boutique, pk=boutique_id)
        return render(
            request,
            'Vendeur/Profil_Boutique.html',
            {
                'boutique': boutique_obj
            }
        )


@never_cache
@user_passes_test(is_vendeur)
def delete_boutique(request, boutique_id):
    get_object_or_404(
        Boutique,
        pk=boutique_id,
        vendeur_bout_id=request.user.vendeur.id
    ).delete()

    return HttpResponse('ok')

Vendeur/templates/Vendeur/Profil_Boutique.html
{% extends 'Base/base.html' %}

{% load static %}
{% load mathfilters %}

{% block title %} Profil Boutique {% endblock %}

{% block contenu %}
    {% with titre_page="Profil Boutique" chemin_page="#" %}
        {% include 'Base/titre_pages.html' %}
    {% endwith %}

    {% with produit_all=boutique.produit_set.all %}
        <div id="content">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <div class="heading">
                            <h2>{{ boutique.nom_bout|capfirst }} Boutique</h2>
                            {% if user.vendeur.id == boutique.vendeur_bout_id.id %}
                                <a href="{% url 'U_Boutique' %}">
                                    <button class="btn btn-lg btn-warning right" style="margin-top: 20px">Modifier
                                        Boutique
                                    </button>
                                </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="row portfolio-project">

                    <section>

                        <div class="col-sm-8">
                            <div class="item">
                                <img src="{% static boutique.logo_bout.url %}" class="img-responsive"
                                     style="max-height: 300px">
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="project-more">
                                <h4>Pays</h4>
                                <p>{{ boutique.pays_bout_id }}</p>
                                <h4>Adresse</h4>
                                <p>{{ boutique.adresse_bout }}</p>
                                <h4>Nombre Produits</h4>
                                <p>{{ produit_all|length }}</p>
                                <h4>Dates Création</h4>
                                <p>{{ boutique.vendeur_bout_id.date_joined|date }}</p>
                            </div>
                        </div>

                    </section>

                    <section>

                        <div class="col-sm-12">

                            <div class="heading">
                                <h3>A Propos De {{ boutique.nom_bout|capfirst }}</h3>
                            </div>

                            <p class="text-justify">{{ boutique.description_bout|linebreaks }}</p>

                        </div>
                    </section>

                </div>

                <section>
                    <div class="row portfolio">

                        <div class="col-md-12">
                            <div class="heading">
                                <h3>Quelque Produit du {{ boutique.nom_bout|capfirst }}</h3>
                            </div>
                        </div>

                        {% for produit in produit_all|slice:":4" %}
                            <div class="col-sm-6 col-md-3">
                                <div class="box-image">
                                    <div class="image">
                                        <img src="{% static produit.image_prod.url %}" alt="" class="img-responsive">
                                    </div>
                                    <div class="bg"></div>
                                    <div class="name" style="height: 55%">
                                        <h3>{{ produit.titre_prod }} -
                                            {% with remise=produit.prix_original_prod|mul:produit.pourcentage_solde_prod|div:100 %}
                                                {{ produit.prix_original_prod|sub:remise|floatformat:"-3" }} TND
                                            {% endwith %}
                                        </h3>
                                    </div>
                                    <div class="text">
                                        <p class="buttons" style="height: 60%">
                                            <a href="{% url 'R_One_Produit' produit_id=produit.id %}"
                                               class="btn btn-template-transparent-primary">Voir</a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </section>

            </div>

        </div>
    {% endwith %}
{% endblock %}

Vendeur/templates/Vendeur/R_All_Boutique.html
{% extends 'Base/base.html' %}

{% load static %}

{% block title %} Liste Boutiques {% endblock %}

{% block contenu %}
    {% with titre_page="Liste Boutiques" chemin_page="Vendeur Pro" %}
        {% include 'Base/titre_pages.html' %}
    {% endwith %}

    <div id="content">
        <div class="container">
            <div class="row">
                <div class="col-md-12" id="blog-listing-small">
                    <div class="row row-flex">

                        {% for boutique in boutiques %}
                            <div class="col-md-3 col-sm-6 {% if not forloop.counter0|divisibleby:3 %}col-md-offset-1{% endif %}">
                                <div class="shop">
                                    <div class="box-image-text blog">
                                        <div class="top">
                                            <div class="image">
                                                <img src="{% static boutique.logo_bout.url %}" class="img-responsive">
                                            </div>
                                            <div class="bg"></div>
                                            <div class="text">
                                                <p class="buttons">
                                                    <a href="{% url "R_Boutique" boutique_id=boutique.id %}"
                                                       class="btn btn-template-transparent-primary">
                                                        <i class="fa fa-link"></i>Profil {{ boutique.nom_bout|upper }}
                                                    </a>
                                                </p>
                                            </div>
                                        </div>
                                        <div class="content">
                                            <h4>
                                                <a href="{% url "R_Boutique" boutique_id=boutique.id %}">{{ boutique.nom_bout|capfirst }}</a>
                                            </h4>
                                            <p class="author-category"><a>{{ boutique.produit_set.all|length }}</a>
                                                Produits en vente actuellement
                                            </p>
                                            <p class="text-justify">{{ boutique.description_bout|truncatechars:120 }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Vendeur/templates/Vendeur/U_Boutique.html
{% extends 'Base/base.html' %}

{% load static %}

{% block title %} Description Boutique {% endblock %}

{% block contenu %}
    {% with titre_page="Description Boutique" chemin_page="Mon Espace Marketplace >  Les Information du Boutique" %}
        {% include 'Base/titre_pages.html' %}
    {% endwith %}

    <div id="content" class="clearfix">
        <div class="container">
            <div class="row">

                <div class="col-md-8 clearfix" id="customer-account">

                    <div class="heading">
                        <h3 class="text-uppercase"> Description Boutique </h3>
                        <a href="{% url "R_Boutique" boutique_id=user.vendeur.boutique.id %}">
                            <button class="btn btn-lg btn-info right" style="margin-top: 20px">
                                Voir Boutique
                            </button>
                        </a>
                    </div>

                    <form method="post" action="{% url "U_Boutique" %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>{{ form.nom_bout.label }}</label>
                                    {{ form.nom_bout }}
                                    {{ form.nom_bout.errors }}
                                </div>
                            </div>
                            <div class="col-sm-5">
                                <div class="form-group">
                                    <label>{{ form.logo_bout.label }}</label>
                                    {{ form.logo_bout }}
                                    {{ form.logo_bout.errors }}
                                </div>
                            </div>
                            <div class="col-sm-1">
                                <div class="image">
                                    {% if form.logo_bout.value %}
                                        <img src="{% static 'files/' %}{{ form.logo_bout.value }}"
                                             class="img-responsive">
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-sm-9">
                                <div class="form-group">
                                    <label>{{ form.adresse_bout.label }}</label>
                                    {{ form.adresse_bout }}
                                    {{ form.adresse_bout.errors }}
                                </div>
                            </div>

                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label>{{ form.pays_bout_id.label }}</label>
                                    {{ form.pays_bout_id }}
                                    {{ form.pays_bout_id.errors }}
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label>{{ form.description_bout.label }}</label>
                                    {{ form.description_bout }}
                                    {{ form.description_bout.errors }}
                                </div>
                            </div>
                            <br>
                            <div class="col-sm-12 text-center">
                                <button type="submit" class="btn btn-template-main">
                                    <i class="fa fa-save"></i> Enregistrer les modifications
                                </button>

                            </div>
                        </div>

                    </form>

                </div>

                {% with boutique_info=True %}
                    {% include 'Customer/menu compte_vendeur.html' %}
                {% endwith %}
            </div>
        </div>
    </div>
    </div>
{% endblock %}

Vendeur/templates/Vendeur/U_Profil_Vendeur.html
{% extends 'Base/base.html' %}

{% block title %} Données personnelles {% endblock %}

{% block contenu %}
    {% with titre_page="Données personnelles" chemin_page="Mon Espace Marketplace > Mes Information de Compte" %}
        {% include 'Base/titre_pages.html' %}
    {% endwith %}

    <div id="content" class="clearfix">
        <div class="container">
            <div class="row">

                <div class="col-md-8 clearfix" id="customer-account">

                    <div class="heading">
                        <h3 class="text-uppercase">Données personnelles</h3>
                    </div>

                    <form method="post" action="{% url "U_Profil_Vendeur" %}">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>{{ form.first_name.label }}</label>
                                    {{ form.first_name }}
                                    {{ form.first_name.errors }}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>{{ form.last_name.label }}</label>
                                    {{ form.last_name }}
                                    {{ form.last_name.errors }}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>{{ form.username.label }}</label>
                                    {{ form.username }}
                                    {{ form.username.errors }}
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>{{ form.email.label }}</label>
                                    {{ form.email }}
                                    {{ form.email.errors }}
                                </div>
                            </div>
                            <br>
                            <div class="col-sm-12 text-center">
                                <button type="submit" class="btn btn-template-main">
                                    <i class="fa fa-save"></i> Enregistrer les modifications
                                </button>

                            </div>
                        </div>

                    </form>

                </div>

                {% with count_info=True %}
                    {% include 'Customer/menu compte_vendeur.html' %}
                {% endwith %}
            </div>
        </div>
    </div>

{% endblock %}